### ISSUE TITLE
failing at node-gyp rebuild

### ISSUE THREAD

**Issue by bhaskar20** [damphat/crc-itu#1]
build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/bitnami/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-71-generic
gyp ERR! command "/opt/bitnami/nodejs/bin/.node.bin" "/opt/bitnami/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/bitnami/apps/logiGpsServer/node_modules/crc-itu
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPEERINVALID mongodb-core@1.2.30 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/opt/bitnami/nodejs/bin/.node.bin" "/opt/bitnami/nodejs/bin/npm" "install"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! crc-itu@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the crc-itu@0.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the crc-itu package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls crc-itu
npm ERR! There is likely additional logging output above.

**Comment by bhaskar20** [comment]
node -v 
5.1.1 
npm -v 
3.3.12

**Comment by Salakar** [comment]
@bhaskar20 If it's of any use, I wrote my own version of this today as there wasn't any working ones around.  Node >= v4.

https://github.com/Salakar/crc16/

**Comment by damphat** [comment]
Great job Salakar, thank you salaka and bhaskar20
The library has been updated on both github and npmjs.
We need node v0.11+ and vc++ or (g++ v4.8+ on linux) to build and install this library.
